### ISSUE TITLE
[feature request] minimal sample for submitting ?

### ISSUE THREAD

**Issue by achanhon** [IRT-SystemX/ml4physim_startingkit#11]
[Updated]

Dear organizer,
I am wondering if you could provide a minimal sample for submitting a single file python implementing the forward + a set of weight.

If I understand well the notebook 6, I need 5 files
- scaler_parameters.py (empty)
- config.ini (empty)
- parameters.json which can be as short as
{
    "evaluateonly": true,
    "scoringonly": true,
    "trained_model": "weight.pth",
    "simulator_config": {
      "simulator_type": "Ransformer",
      "simulator_file": "ransformer",
      "name": "Ransformer",
      "model": "Ransformer",
      "model_type": "Ransformer",
      "scaler_type": "None",
      "scaler_file": "None",
      "scaler_class": "None",
      "scaler": "None",
      "config_name": "DEFAULT",
    }
  }
- a file containing the weigths (weight.pth)
- a single python file ransformer.py that implement the model by modifying the less possible the example of notebook 4 section 2 (the class MyCustomFullyConnected)

However, it does not work: the first error is a missing file "json_metrics.json".
Regards

**Comment by JiayiCC** [comment]
Hello,

I had similar issues on my side. An error raised from the injection program when submitting the "simple" submission example in the "submission" directory: 

```
Traceback (most recent call last):
  File "/app/program/ingestion.py", line 246, in <module>
    architecture_type=simulator_parameters["architecture_type"],
KeyError: 'architecture_type'
```

**Comment by jpbrunetsx** [comment]
Hi,
 
We have now implemented new examples that should cover this use case : https://github.com/IRT-SystemX/ml4physim_startingkit/blob/main/7_Submission_examples.ipynb example 3 and 4. 
Example 3 correspond to the submission of a custom model and example 4 to the evaluation of a pre-trained custom model. Please note that in order to be eligible for the final ranking all model will need to be trained and evaluated through the submission process.
 
In case you would need packages that are not available at the moment don't hesitate to contact us and we will evaluate the feasability.
 
Concerning JiayiCC issue, it was linked to a change in the implementation of the scaler the submission examples should be now corrected.
 
Best regards

**Comment by achanhon** [comment]
First, I want to thank the organizers for this benchmark and for having added the "simple-submission" example.

Yet, I still struggle a bit with the submission.
In order to debug, I have even just copy-paste the provided sample my_augmented_simulator.py + parameters.json with _"evaluateonly": true,_ but it still does not work with the output :


```
Traceback (most recent call last):
==========
  File "/app/program/ingestion.py", line 143, in <module>
== CUDA ==
    raise ModelApiError("Missing results.json file")
==========
__main__.ModelApiError: Missing results.json file

CUDA Version 11.7.0

Container image Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Traceback (most recent call last):
==========
  File "/app/program/score.py", line 123, in <module>
== CUDA ==
    metrics = import_metrics(input_dir)
==========
  File "/app/program/score.py", line 38, in import_metrics

    raise ModelApiError("Missing json_metrics.json file")
CUDA Version 11.7.0
__main__.ModelApiError: Missing json_metrics.json file

Container image Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved. 
```

just bellow the submission zip (but it is just a copy paste of https://github.com/IRT-SystemX/ml4physim_startingkit/blob/main/7_Submission_examples.ipynb -> #example 4)
it seems that _"evaluateonly": true,"_ is not working... 

[baseline.zip](https://github.com/IRT-SystemX/ml4physim_startingkit/files/14063035/baseline.zip)

**Comment by jpbrunetsx** [comment]
In the provided submission, scoringonly is set to true, it override the evaluateonly parameter and the ingestion module is trying to find results.json. 

A full example is available here : https://github.com/IRT-SystemX/ml4physim_startingkit/tree/main/submission/load_trained_model
